create table public.pomodoros_tasks (
  id bigint generated by default as identity primary key,
  pomodoro_id bigint not null references public.pomodoros(id) on delete cascade,
  task_id uuid not null references public.tasks(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (pomodoro_id, task_id)
);

alter table public.pomodoros_tasks enable row level security;

create policy "Users can view their own pomodoro tasks"
on public.pomodoros_tasks for select
using (auth.uid() = user_id);

create policy "Users can insert their own pomodoro tasks"
on public.pomodoros_tasks for insert
with check (auth.uid() = user_id);

create policy "Users can delete their own pomodoro tasks"
on public.pomodoros_tasks for delete
using (auth.uid() = user_id);
